=== Shivamverma446444/Assisnments/Day-18/Books.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.booksinfo.com">
	<xsd:element name="books">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="book" minOccurs="1" maxOccurs="2">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element name="bid" type="xsd:int"/>
					<xsd:element name="bname" type="xsd:string"/>
					<xsd:element name="author" type="xsd:string"/>
					<xsd:element name="publisher" type="xsd:string"/>
				</xsd:sequence>
			</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Shivamverma446444/Assisnments/Desktop/HCL Training/Java/Day-18/book.xml
<?xml version="1.0" encoding="utf-8"?>
<b:books xmlns:xi="http://www.w3.org/2001/XMLSchema-instance" xmlns:b="http://www.booksinfo.com" xi:schemaLocation="http://www.booksinfo.com books.xsd">
  <book>
		<bid>101</bid>
		<bname>Harry Potter</bname>
		<author>JK Rowling</author>
		<publisher>Magic Book</publisher>
	</book>
	<book>
		<bid>102</bid>
		<bname>Wings of Fire</bname>
		<author>Abdul Kalam</author>
		<publisher>Motivation</publisher>
	</book>
</b:books>
